### PR TITLE
Grid auto unit 14

### PR DESCRIPTION
**Pull request by jeff-dh**
this is based on top of (includes) #15

### CODE REVIEW

**Comment by jreiberkyle** [comment]
Nice add!

An essential role of the grid for my workflow is actually calculating the dimensions of the object. So, knowing the grid unit is essential. Grid autoscaling is great for visualization but, without some reporting of what the determined grid unit is, it destroys the ability to calculate dimensions. 

For now, keep the default behavior (grid unit = 1) and allow for autoscaling if grid_unit is set to 0 (and add appropriate documentation of the new behavior to render and visualize_stl).

**Comment by jeff-dh** [comment]
Well... the unit ist always 10**x so you can still use it for
dimension calculations you just have to "guess" (and I assume it should
be obvious) the unit-scale.

Anyway, I can have a look at pythreejs whether there's something like a
hud or similar.

grid_unit = 0 does not work to enable auto scaling, because it's use
to disable the grid. So it has to be -1 -> GRID_AUTO_UNIT. You could
also add an extra parameter, but actually I think you want auto scaling
to be enabled by default, for example take a look at openscad itself.

**Comment by jreiberkyle** [comment]
A HUD would be great for many reasons, displaying units being one of them (labeling axes being another). That is a bigger endeavor and not in scope for v1 BUT I would love to collaborate with you to set the vision for a HUD for v2! Good point on 0 being taken. -1 as a value to enable autoscaling works. Just use docs to convey this instead of a new global var.

**Comment by jreiberkyle** [comment]
Autogridding works great (see examples below). It's not trivial to understand how the autogridding works. Could you add a description to the docs? Once that's in, it's clear to merge.

30x30x30 cube (-15 to 15 in each dim)
image

3x3x3 cube (-1.5 to 1.5 in each dim)
image

6x6x6 cube (3 to 3 in each dim)
image

**Comment by jeff-dh** [comment]
Would you add the docs section on your own? :-p

I don't know what kind of doc you like (for it).... I wouldn't document it at all :-p

**Comment by jreiberkyle** [comment]
I added a reference to autogridding in the [usage docs](https://jreiberkyle.github.io/jupyterscad/usage/#adjusting-grid-size).

**Comment by jreiberkyle** [comment]
ok now that I am back to actually using jupyterscad in a real way, auto-grid is definitely going to be the default 😆

**Comment by jeff-dh** [comment]
;)

**Pull request merged**
